server:
  port: ${PORT:5001}

jwt:
  secrete: ${JWT_SECRETE:UmPOgUMOK4bhoq4ohY41F2GQIo0k0qUcr6ewfh0t3is}
  lifetime: 30m

base-url: /api

spring:
  application:
    name: spring_app

  liquibase:
    #    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop

rollbar:
  access-token: ${ROLLBAR_ACCESS_TOKEN:8ca93a30234349f5b0a3cd31f8723fe3}